### ISSUE TITLE
CORS, empty post ... and current status

### ISSUE THREAD

**Issue by jim108dev** [Woody88/purescript-swerve#5]
Hi! Thank you for creating this library. I have just glanced over the tests and I have a few questions. 
- Can CORS requests handled easily? meaning
   - Getting `Origin:..` and adding `Access-Control-Allow-Origin:...` to the response for every request.
   - OPTION requests for every PUT, POST, DELETE created with a wildcard.
- With PureScript Payload I had some issues with empty POST requests. Is this supported?
- For Development it might be useful to show a detailed error response, for production just a status code. Is this possible?
- What is the current status of the project?

Thanks.

**Comment by Woody88** [comment]
Hi @jim108dev! 

1. I actually need to fix the README.md `Sweve` is a library that offers a DSL for describing server and client web applications. [Warp](https://github.com/Woody88/purescript-warp) is actually the server library that is used for running your server.  So, you can easily solve your CORS problem by just adding the CORS middleware to your Warp server. Warp supports expressjs middleware, so you can just use expressjs's cors middleware. [Here](https://github.com/Woody88/purescript-warp/issues/5#issuecomment-754348852) is an example.
2. As long as you don't define a request body in your endpoint specification you can make a POST request with an empty body. I've updated the tests, please refer to [this](https://github.com/Woody88/purescript-swerve/blob/master/test/Server/Verb.purs#L39-L45) test.
3. The library already returns the correct error message for each status code. I think what you need is a request logger library that allows you to log your HTTP request to the console. Once again, that is something that needs to be set in Warp. You can either add a middleware such as [morgan](https://github.com/expressjs/morgan) or you can use [wai-logger](https://github.com/Woody88/purescript-wai-logger).
4. The goal is to cover most of the features that the Haskell version offers - now that PS 0.14 is finally released I should be able to release a version. I couldn't release anything earlier because this project is built using features that are only existing in PS 0.14 and above.

Hope this answers your questions.

P.S: you should have a look at [Wai](https://github.com/Woody88/purescript-wai) which is the core library for Warp.
